version: '3.0'

services:
    mariadb:
        image: 'mariadb'
        build: ./requirements/mariadb/
        ports:
            - 3306:3306
        env_file:
            - ./.env
        restart: always
        volumes:
            - db_db:/var/lib/mysql
        networks:
            - intra
    wordpress:
        build: ./requirements/wordpress
        volumes:
            - www_db:/var/www
        expose:
            - 9000:9000
        depends_on:
            - mariadb
        networks:
            - intra
        env_file:
            - ./.env
        restart: always

    nginx:
        build: ./requirements/nginx
        volumes:
            - www_db:/var/www
        networks:
            - intra    
        ports:
            - 443:443
        env_file:
            - ./.env
        depends_on:
            - wordpress
        restart: always

volumes:
    db_db:
        name: db_db
        driver: local
        driver_opts:
            type: none
            device: /Users/gangjiho/test/db
            o: bind
    www_db:
        name: www_db
        driver: local
        driver_opts:
            type: none
            device: /Users/gangjiho/test/wp
            o: bind

networks:
    intra:
        driver: bridge