version: "3.0"

services:
  mariadb:
    image: 'mariadb'
    build: ./requirements/mariadb/
    ports:
      - 3306:3306
    env_file:
      - ./.env
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - intra
  wordpress:
    image: 'wordpress'
    build: ./requirements/wordpress/
    ports:
      - 9000:9000 
    env_file:
      - ./.env
    volumes:
      - www-v:/var/www
    networks:
      - intra
    depends_on:
      - mariadb
    restart: always

  nginx:
    image: 'nginx'
    build: ./requirements/nginx/
    ports:
      - 443:443
    volumes:
      - www-v:/var/www
    depends_on:
      - wordpress
    restart: always
    networks:
      - intra

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      device: /Users/gangjiho/data/db
      o: bind
  www-v:
    name: www-v
    driver: local
    driver_opts:
      type: none
      device: /Users/gangjiho/data/wp
      o: bind

networks:
  intra:
    driver: bridge