version: "3.0"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    ports:
      - 3306:3306
    env_file:
      - ./.env
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - intra
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    ports:
      - 9000:9000 
    env_file:
      - ./.env
    volumes:
      - db_wp:/var/www
    networks:
      - intra
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    volumes:
      - db_wp:/var/www
    depends_on:
      - wordpress
    restart: always
    networks:
      - intra

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      device: /home/test/db
      type: none
      o: bind
  db_wp:
    name: db_wp
    driver: local
    driver_opts:
      device: /home/test/wp
      type: none
      o: bind
      

networks:
  intra:
    driver: bridge